# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app_bundle.security_listener:
        class: AppBundle\EventListener\SecurityListener
        arguments: ['@service_container']
        tags:
          - { name: kernel.event_subscriber }
    app_bundle.project_voter:
        class: AppBundle\Security\ProjectVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }
    app.form.type.comment:
        class: AppBundle\Form\Type\CommentType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
          - { name: form.type }
    twig.extension.date_time_time_zone:
        class: AppBundle\Twig\DateTimeTimeZoneExtension
        arguments: ['@service_container']
        tags:
          - { name: twig.extension }
